server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/${MYSQL_DATABASE:plip_topic}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

eureka:
  instance:
    hostname: topic
    prefer-ip-address: false
    instance-id: ${spring.application.name}:docker:${server.port}
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
